### ISSUE TITLE
Route prefix for Controllers

### ISSUE THREAD

**Issue by adaojunior** [emilniklas/embla#1]
First of all, thank you for another awesome library.
I think it would be nice to have something like a route prefix for controllers.

```
@RoutePrefix('api/auth')
class AuthController extends Controller {

   /// POST /api/auth/login
  @Post() login() { ... }

   /// ANY /api/auth/logout
  @All() logout() { ... }

}

```

I'm calling it `RoutePrefix` but I think you may have a better idea for it.

**Comment by emilniklas** [comment]
This is from the README:

Since controllers are middleware too, we can easily route our controllers to endpoints like this:

```
Route.all('pages/*', PagesController)
```

Is this is confusing, you think?

**Comment by adaojunior** [comment]
Huuum, I'm not sure, for now I'll use it if someday I find it confusing I'll reopen this issue :D
