### ISSUE TITLE
Set header

### ISSUE THREAD

**Issue by indiealexh** [emilniklas/embla#2]
Do you have a built in way currently to set and read header variables?
Such as cors, application type, authentication headers etc?

I would like to use Embla for creating rest services, including versioning and authentication if I can.

**Comment by emilniklas** [comment]
Hey, @indiealexh!

Embla uses [Shelf](https://pub.dartlang.org/packages/shelf) for the HTTP request/response cycle.

You can return Shelf responses directly in handlers, and `embla/http.dart` exposes that class, so to add headers you can do this:

```
import 'package:embla/http.dart';
export 'package:embla/bootstrap.dart';

get embla => [
  new HttpBootstrapper(
    pipeline: pipe(
      () => new Response.ok('Hello!', headers: {
            'Content-Type': 'text/plain'
          })
    )
  )
];
```

Check out the Shelf documentation for more details about the Response class.

**Comment by emilniklas** [comment]
Oh, and to read from the request you can use Dependency Injection to inject the Shelf `Request` object. Simply add `Request request` to the parameter list of your handler function to receive it:

``` dart
pipe(
  (Request request) {
    return request.headers; // returns the request headers as JSON
  }
)
```

**Comment by indiealexh** [comment]
Excellent, Seems like Embla will fit my needs quite nicely.
