### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by Scorpiion** [emilniklas/embla#8]
Hi Emil, I just wanted to check what the status of Embla is? I'm making a list of Dart server side frameworks and I'm not sure if I should include Embla or not. Is the low activity just because your pretty happy with the design as it is, or you simply been busy or was/is Embla more of an experiment that no longer is under development?

_Ps. I'm not including Bridge on said list because of you [earlier post](https://medium.com/@emilniklas/the-bridge-framework-is-being-discontinued-5c3e5c5ad8cc) Ds._

Cheers, Robert

**Comment by emilniklas** [comment]
Hi Robert.

The main reason for inactivity is focus on work and other projects. However, I do feel quite confident in the current version of Embla and I intend to maintain the project if issues should arise.

I'l very much like Embla to be part of this list, but Bridge should be excluded, yes.

The documentation is lacking right now. But as Embla is a much smaller project than Bridge was (in scope), all you need to know should be in the README of this repo.

**Comment by Scorpiion** [comment]
Okay, I understand, yeah it's always hard to find the time for proper documentation. Great to hear your positive response, I will include embla on the list.
